SELECT GEA.HSCODE
,GEA.COMMODITY_CODE
--COMMODITY DESCRIPTION
,COM.COMMODITY
,GEA.STATE_CODE
--COUNTRY DESCRIPTION
,COUNTRY.COUNTRY_DESCRIPTION
,GEA.SUPPLIER_CODE
--SUPPLIER DESCRIPTION
,SUP.SUPPLIER_DESCRIPTION
,GEA.REGION_CODE
--REGION DESCRIPTION
,REG.REGION_DESCRIPTION
,GEA.COUNTRY_CODE
--COUNTRY DESCRIPTION
,COUNTRY.COUNTRY_DESCRIPTION
,GEA.QUANTITY
,GEA.EXPORTED_TO_CODE
--EXPORTED TO DESCRIPTION
,EXPO.EXPORTED_TO_DESCRIPTION
,GEA.EXPORTED_MONTH
--CALENDAR INFORMATION
,CAL.[MONTH]
,CAL.[QUARTER]
,CAL.SHORT_MONTH
,CAL.YEAR_MONTH
,CAL.YEAR_QUARTER
,GEA.[YEAR]
,GEA.EXPORT_MODE
,GEA.MATERIAL_TYPE_CODE
--MATERIAL TYPE
,MAT.MATERIAL_TYPE
,GEA.UNIT_OF_MEASURE_UOM
,GEA.FROM_CURRENCY
--EXCHNAGE RATE
,EXC.EXCHANGE_RATE
,GEA.TO_CURRENCY
--ROUND OFF THE PRICE TO TWO DECIMALS
,ROUND(GEA.PRICE,2) AS PRICE
,GEA.FREIGHT_CHARGES_IN

---1.	TOTAL SALES = PRICE*QUANTITY
,ROUND(GEA.PRICE,2)*GEA.QUANTITY AS 'TOTAL SALES'

---2.	FREIGHT CHARGES = TOTAL SALES * FREIGHT CHARGES/100
,ROUND(GEA.PRICE,2)*GEA.QUANTITY*((GEA.FREIGHT_CHARGES_IN)/100) AS 'FREIGHT CHARGES'

---3.	DUTY CHARGES = TOTAL SALES* DUTY CHARGES/100
,CASE
      WHEN GEA.QUANTITY BETWEEN 1 AND 25 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.005
      WHEN GEA.QUANTITY BETWEEN 26 AND 50 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.01
      WHEN GEA.QUANTITY BETWEEN 51 AND 100 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.015
      WHEN GEA.QUANTITY BETWEEN 101 AND 200 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.02
      WHEN GEA.QUANTITY > 200 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.025
      ELSE 0
 END AS 'DUTY CHARGES'
    
--- 4. TOTAL COST TO COMPANY = TOTAL SALES + FREIGHT CHARGES + DUTY CHARGES
,(ROUND(GEA.PRICE, 2) * GEA.QUANTITY) + 
 (ROUND(GEA.PRICE, 2) * GEA.QUANTITY * (GEA.FREIGHT_CHARGES_IN / 100)) + 
  CASE
      WHEN GEA.QUANTITY BETWEEN 1 AND 25 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.005
      WHEN GEA.QUANTITY BETWEEN 26 AND 50 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.01
      WHEN GEA.QUANTITY BETWEEN 51 AND 100 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.015
      WHEN GEA.QUANTITY BETWEEN 101 AND 200 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.02
      WHEN GEA.QUANTITY > 200 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.025
      ELSE 0
  END AS 'TOTAL COST TO COMPANY'

---5.	NET SALES = TOTAL SALES - FREIGHT CHARGES - DUTY CHARGES 
,(ROUND(GEA.PRICE, 2) * GEA.QUANTITY) - 
 (ROUND(GEA.PRICE, 2) * GEA.QUANTITY * (GEA.FREIGHT_CHARGES_IN / 100)) - 
  CASE
      WHEN GEA.QUANTITY BETWEEN 1 AND 25 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.005
      WHEN GEA.QUANTITY BETWEEN 26 AND 50 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.01
      WHEN GEA.QUANTITY BETWEEN 51 AND 100 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.015
      WHEN GEA.QUANTITY BETWEEN 101 AND 200 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.02
      WHEN GEA.QUANTITY > 200 THEN ROUND(GEA.PRICE, 2) * GEA.QUANTITY * 0.025
      ELSE 0
  END AS 'NET SALES'

---NAMIBIA NM AND MOROCCO MO   FALLS UNDER EAST AFRICA BUILD A NEW HIERARCHY
,CASE
	WHEN COUNTRY.COUNTRY_CODE ='NM' OR COUNTRY.COUNTRY_CODE ='MA' THEN 'EAST AFRICA'
	ELSE REG.REGION_DESCRIPTION
	END AS 'REGION NEW'
---REPLACE MATERIAL TYPE NA WITH  UNDER PROCESSING 
,CASE
	WHEN MAT.MATERIAL_TYPE = 'NA' THEN 'UNDER PROCESSIONG'
	ELSE MAT.MATERIAL_TYPE
	END AS 'MATERIAL TYPE NEW'

FROM [EXP-FCT-EXPORTS ANALYSIS] AS GEA


LEFT JOIN [DIM-COMMODITY] AS COM
ON GEA.COMMODITY_CODE = COM.COMMODITY_CODE

LEFT JOIN [DIM-COUNTRY] AS COUNTRY
ON GEA.COUNTRY_CODE = COUNTRY.COUNTRY_CODE

LEFT JOIN [DIM-CALENDAR] AS CAL
ON GEA.EXPORTED_MONTH = CAL.EXPORTED_MONTH

LEFT JOIN [DIM-EXCHANGE RATE] AS EXC
ON GEA.FROM_CURRENCY = EXC.FROM_CURRENCY

LEFT JOIN [DIM-EXPORTED TO] AS EXPO
ON GEA.EXPORTED_TO_CODE = EXPO.EXPORTED_TO_CODE

LEFT JOIN [DIM-MATERIAL TYPE] AS MAT
ON GEA.MATERIAL_TYPE_CODE = MAT.MATERIAL_CODE

LEFT JOIN [DIM-REGION] AS REG
ON GEA.REGION_CODE = REG.REGION_CODE

LEFT JOIN [DIM-STATE] AS STA
ON GEA.STATE_CODE = STA.STATE_CODE

LEFT JOIN [DIM-SUPPLIER] AS SUP
ON GEA.SUPPLIER_CODE = SUP.SUPPLIER_CODE

LEFT JOIN [DIM-TRANSPORTATION] AS TRANS
ON GEA.EXPORT_MODE = TRANS.EXPORT_MODE

--EXCLUDE GOLD, IRON AND STEEL FROM THE ANALYSIS WHERE IT FALLS 
WHERE COM.COMMODITY NOT IN('IRON AND STEEL','GOLD')